#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cargo
#
Name     : pypi-rpds_py
Version  : 0.9.2
Release  : 2
URL      : https://files.pythonhosted.org/packages/da/3c/fa2701bfc5d67f4a23f1f0f4347284c51801e9dbc24f916231c2446647df/rpds_py-0.9.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/da/3c/fa2701bfc5d67f4a23f1f0f4347284c51801e9dbc24f916231c2446647df/rpds_py-0.9.2.tar.gz
Source1  : http://localhost/cgit/vendor/pypi-rpds_py/snapshot/pypi-rpds_py-2023-07-31-16-08-27.tar.xz
Summary  : Python bindings to Rust's persistent data structures (rpds)
Group    : Development/Tools
License  : Apache-2.0 MIT MPL-2.0-no-copyleft-exception Unicode-DFS-2016
Requires: pypi-rpds_py-license = %{version}-%{release}
Requires: pypi-rpds_py-python = %{version}-%{release}
Requires: pypi-rpds_py-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(maturin)
BuildRequires : pypi-maturin
BuildRequires : rustc
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
===========
``rpds.py``
===========
|PyPI| |Pythons| |CI|
.. |PyPI| image:: https://img.shields.io/pypi/v/rpds-py.svg
:alt: PyPI version
:target: https://pypi.org/project/rpds-py/

%package license
Summary: license components for the pypi-rpds_py package.
Group: Default

%description license
license components for the pypi-rpds_py package.


%package python
Summary: python components for the pypi-rpds_py package.
Group: Default
Requires: pypi-rpds_py-python3 = %{version}-%{release}

%description python
python components for the pypi-rpds_py package.


%package python3
Summary: python3 components for the pypi-rpds_py package.
Group: Default
Requires: python3-core
Provides: pypi(rpds_py)

%description python3
python3 components for the pypi-rpds_py package.


%prep
%setup -q -n rpds_py-0.9.2
cd %{_builddir}
tar xf %{_sourcedir}/pypi-rpds_py-2023-07-31-16-08-27.tar.xz
cd %{_builddir}/rpds_py-0.9.2
mkdir -p ./vendor
cp -r %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/* %{_builddir}/rpds_py-0.9.2/./vendor
mkdir -p .cargo
echo '[source.crates-io]' >> .cargo/config.toml
echo 'replace-with = "vendored-sources"' >> .cargo/config.toml
echo '[source.vendored-sources]' >> .cargo/config.toml
echo 'directory = "vendor"' >> .cargo/config.toml

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-rpds_py
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/archery/LICENSE.md %{buildroot}/usr/share/package-licenses/pypi-rpds_py/7c1853ff34974a6b19247c039a0f60e06438f877 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-rpds_py/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-rpds_py/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-rpds_py/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/indoc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/indoc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-rpds_py/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-rpds_py/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/lock_api/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/lock_api/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-rpds_py/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/memoffset/LICENSE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/02bf11a87b9bbacedf2fcf4856af3b933faef82e || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-rpds_py/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/parking_lot/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/parking_lot/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-rpds_py/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/parking_lot_core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/parking_lot_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-rpds_py/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-rpds_py/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/pyo3-build-config/LICENSE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/pyo3-macros-backend/LICENSE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/pyo3-macros/LICENSE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/pyo3/LICENSE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-rpds_py/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/redox_syscall/LICENSE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/a00165152c82ea55b9fc254890dc8860c25e3bb6 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/rpds/LICENSE.md %{buildroot}/usr/share/package-licenses/pypi-rpds_py/7c1853ff34974a6b19247c039a0f60e06438f877 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/scopeguard/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/scopeguard/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-rpds_py/f498d95a48889a0b1432e420e6754881eff1d593 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/smallvec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/smallvec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-rpds_py/c61640f6c218caf86d1b8072e09668a8362dba04 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/static_assertions/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/static_assertions/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-rpds_py/972723ef8f594b1c7515e4c227ff9d5912041fac || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-rpds_py/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/target-lexicon/LICENSE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-rpds_py/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/unindent/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/unindent/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-rpds_py/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/windows-targets/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-rpds_py/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/windows-targets/license-mit %{buildroot}/usr/share/package-licenses/pypi-rpds_py/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/windows_aarch64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-rpds_py/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/windows_aarch64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-rpds_py/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/windows_aarch64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-rpds_py/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/windows_aarch64_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-rpds_py/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/windows_i686_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-rpds_py/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/windows_i686_gnu/license-mit %{buildroot}/usr/share/package-licenses/pypi-rpds_py/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/windows_i686_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-rpds_py/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/windows_i686_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-rpds_py/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/windows_x86_64_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-rpds_py/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/windows_x86_64_gnu/license-mit %{buildroot}/usr/share/package-licenses/pypi-rpds_py/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/windows_x86_64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-rpds_py/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/windows_x86_64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-rpds_py/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/windows_x86_64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-rpds_py/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-rpds_py-2023-07-31-16-08-27/windows_x86_64_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-rpds_py/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/rpds_py-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-rpds_py/bc513368a1b86cbe2019fa846ae9b49a86631339 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-rpds_py/02bf11a87b9bbacedf2fcf4856af3b933faef82e
/usr/share/package-licenses/pypi-rpds_py/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/pypi-rpds_py/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/pypi-rpds_py/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/pypi-rpds_py/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/pypi-rpds_py/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/pypi-rpds_py/5bb5828e544f63bd76c1b7112981a1ad86ae77f9
/usr/share/package-licenses/pypi-rpds_py/689ec0681815ecc32bee639c68e7740add7bd301
/usr/share/package-licenses/pypi-rpds_py/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/pypi-rpds_py/7c1853ff34974a6b19247c039a0f60e06438f877
/usr/share/package-licenses/pypi-rpds_py/972723ef8f594b1c7515e4c227ff9d5912041fac
/usr/share/package-licenses/pypi-rpds_py/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7
/usr/share/package-licenses/pypi-rpds_py/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/pypi-rpds_py/a00165152c82ea55b9fc254890dc8860c25e3bb6
/usr/share/package-licenses/pypi-rpds_py/a3b3a65335e78bde163f84d599fa899776552994
/usr/share/package-licenses/pypi-rpds_py/bc513368a1b86cbe2019fa846ae9b49a86631339
/usr/share/package-licenses/pypi-rpds_py/c61640f6c218caf86d1b8072e09668a8362dba04
/usr/share/package-licenses/pypi-rpds_py/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/pypi-rpds_py/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/pypi-rpds_py/f137043e018f2024e0414a9153ea728c203ae8e5
/usr/share/package-licenses/pypi-rpds_py/f498d95a48889a0b1432e420e6754881eff1d593

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
